sudo: required

services:
    - docker

before_install:
    - docker build -t raychanks/docker-react -f Dockerfile.dev .

script:
    - docker run raychanks/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-135298415474"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
